import type { StoryOutputInput } from '@bookmagic/shared';

export function getZooAdventureGirlStory(childName: string, childAge: number, childGender: string): StoryOutputInput {
  return {
    title: `${childName}'s Magical Zoo Adventure!`,
    pages: [
      {
        pageNumber: 1,
        text: `${childName}'s Magical Zoo Adventure!`,
        imagePrompt: 'A decorative storybook title page with elegant golden zoo gates adorned with flowering vines framing the edges, glowing colorful animal auras in soft blue gold pink and silver floating through the air, lush tropical plants and vibrant flowers bordering the page, a magical sparkling path leading through the gates, warm inviting golden light with soft pink highlights',
        sceneDescription: 'Title page with magical zoo-themed decorations',
        layout: 'chapter-title' as const,
        imageComposition: 'chapter-title: decorative border with zoo gates and glowing auras',
      },
      {
        pageNumber: 2,
        text: `One bright morning, ${childName} skipped through the tall golden gates of the Whispering Zoo. Something felt different today. The air shimmered with tiny flecks of light, and she could feel a warm tingle in her chest.`,
        imagePrompt: 'Tall ornate golden zoo gates opening into a magical pathway lined with lush tropical plants and colorful blooming flowers in pink purple and yellow, tiny golden light particles floating in the air like fireflies in daytime, a cobblestone path winding ahead into a vibrant green landscape, warm morning sunlight streaming through the gates casting long golden rays, shimmering magical atmosphere with soft pink and gold bokeh',
        sceneDescription: `${childName} enters the magical Whispering Zoo`,
        layout: 'full-bleed-text-bottom' as const,
        imageComposition: 'keep main subject in upper two-thirds, simpler background at bottom for text',
      },
      {
        pageNumber: 3,
        text: `As ${childName} rounded the first corner, she gasped. Every animal in the zoo was surrounded by a softly glowing aura of color! A sign by the path read: "Today, the animals share their feelings through light."`,
        imagePrompt: 'A wide cobblestone zoo pathway with lush green hedges on both sides topped with blooming flowers, multiple animal enclosures visible in the distance each radiating soft colorful glowing auras in blue gold pink and silver, an ornate wooden sign with golden lettering beside the path adorned with painted butterflies, magical sparkles drifting upward from the enclosures, bright blue sky with fluffy white clouds, vibrant and enchanting atmosphere',
        sceneDescription: `${childName} discovers the animals have glowing auras`,
        layout: 'full-bleed-text-top' as const,
        imageComposition: 'keep main subject in lower two-thirds, simpler background at top for text',
      },
      {
        pageNumber: 4,
        text: `The first enclosure held a magnificent elephant. But unlike the other animals, its aura glowed a deep, lonely blue. The elephant stood apart, its trunk curled sadly. ${childName} felt her heart ache just looking at it.`,
        imagePrompt: 'A large majestic African elephant standing alone in a spacious lush green enclosure, surrounded by a deep melancholy blue glowing aura that pulses gently, the elephant trunk curled downward with sad drooping ears, tall acacia trees in the background, soft blue light casting shadows on the ground, other distant warm glows visible from neighboring enclosures contrasting with the blue sadness, emotional and tender atmosphere',
        sceneDescription: `${childName} meets the lonely elephant with a blue aura`,
        layout: 'image-left-text-right' as const,
        imageComposition: 'place subject on the LEFT side, leave right side as soft background',
      },
      {
        pageNumber: 5,
        text: `"Why are you so sad?" ${childName} whispered. The elephant looked at her with wise, ancient eyes. Somehow, she understood: the elephant had been separated from her herd long ago and missed them terribly.`,
        imagePrompt: 'A close-up view of a large elephant face with wise ancient amber eyes glistening with emotion, a deep blue glowing aura surrounding the elephant like gentle mist, a single tear trailing down the wrinkled grey skin, soft warm background light filtering through acacia tree branches, intimate and emotional atmosphere, beautiful detail on elephant skin texture and long eyelashes, blue aura particles drifting gently',
        sceneDescription: `${childName} senses the elephant's loneliness`,
        layout: 'full-bleed-text-center' as const,
        imageComposition: 'place subjects at edges/sides, keep center softer for text readability',
      },
      {
        pageNumber: 6,
        text: `${childName} promised the elephant she would help. But first, the zoo had more wonders to show her. She followed the sparkly path to a crystal-blue lagoon where dolphins leaped and twirled, their auras streaming with joyful turquoise light!`,
        imagePrompt: 'A beautiful crystal-clear turquoise lagoon surrounded by tropical plants and colorful flowers, three playful dolphins leaping in graceful arcs above the sparkling water, each trailing streams of brilliant turquoise and aqua glowing light like ribbons, water droplets catching the light like diamonds, rainbow mist from the splashes, joyful and energetic atmosphere, warm sunlight making the water sparkle',
        sceneDescription: `${childName} discovers the playful dolphins with turquoise auras`,
        layout: 'full-bleed-text-bottom' as const,
        imageComposition: 'keep main subject in upper two-thirds, simpler background at bottom for text',
      },
      {
        pageNumber: 7,
        text: `The dolphins spun and danced in the water, their turquoise glow leaving spirals of light on the surface. One dolphin splashed playfully, sending a shower of glowing droplets into the air that landed like tiny stars on the ground near ${childName}.`,
        imagePrompt: 'A dolphin bursting from crystal blue water with a joyful open mouth, turquoise aura streaming behind it, hundreds of glowing water droplets suspended in the air like tiny stars, spiral patterns of turquoise light on the water surface, lush tropical plants framing the lagoon edges, brilliant sunlight creating prismatic rainbows in the spray, magical and playful atmosphere, sparkling droplets landing on nearby stones',
        sceneDescription: 'A dolphin splashes glowing droplets near the path',
        layout: 'image-right-text-left' as const,
        imageComposition: 'place subject on the RIGHT side, leave left side as soft background',
      },
      {
        pageNumber: 8,
        text: `Next, ${childName} came to a tall ancient tree where three wise owls perched on mossy branches. Their auras shimmered with calm silver light that seemed to whisper secrets of the forest.`,
        imagePrompt: 'A magnificent ancient gnarled tree with thick mossy branches in a quiet corner of the zoo, three wise owls with large luminous golden eyes perched on different branches, each surrounded by a shimmering silver aura that radiates peaceful wisdom, silver light particles drifting slowly downward like gentle snow, soft purple twilight atmosphere despite being daytime, mystical and serene mood, intricate bark texture with glowing green moss',
        sceneDescription: `${childName} meets the wise owls with silver auras`,
        layout: 'dramatic-image-only' as const,
        imageComposition: 'full cinematic composition, owls as the main subjects on the ancient tree, no humans',
      },
      {
        pageNumber: 9,
        text: `The owls blinked slowly at ${childName}. Through their silver glow, she understood their message: "The lonely elephant's herd is in the sanctuary beyond the hill. She needs only to hear their call." ${childName} knew what she had to do.`,
        imagePrompt: 'Three majestic owls with piercing golden eyes on a mossy branch, silver aura intensifying around them as silver light streams outward in gentle waves carrying tiny symbol-like patterns, a faint image of rolling green hills visible in the silver mist behind them, mystical ancient tree bark covered in soft glowing moss, ethereal and wise atmosphere, silver particles forming a path pointing toward distant hills',
        sceneDescription: 'The owls reveal the location of the elephant herd',
        layout: 'full-bleed-text-bottom' as const,
        imageComposition: 'keep main subject in upper two-thirds, simpler background at bottom for text',
      },
      {
        pageNumber: 10,
        text: `On her way back to the elephant, ${childName} stopped at the penguin pool. A tiny baby penguin stood at the edge of the water, its little flippers trembling. Its aura flickered nervously between pale blue and soft white as it tried to work up the courage to swim.`,
        imagePrompt: 'An adorable fluffy baby penguin standing at the edge of a sparkling pool of clear blue water, its tiny flippers outstretched nervously, a flickering aura shifting between pale blue and soft white around its small body, smooth rocks around the pool edge, crystal clear water with light dancing on the bottom, other penguins swimming happily in the background with steady blue auras, endearing and sweet atmosphere',
        sceneDescription: `${childName} watches a baby penguin afraid to swim`,
        layout: 'image-left-text-right' as const,
        imageComposition: 'place subject on the LEFT side, leave right side as soft background',
      },
      {
        pageNumber: 11,
        text: `${childName} clapped her hands gently. "You can do it, little one!" The baby penguin puffed up its chest, waddled forward, and plopped into the water with a tiny splash. Its aura burst into a brilliant happy blue as it paddled its first strokes!`,
        imagePrompt: 'A baby penguin splashing joyfully in crystal blue water with its tiny flippers paddling, surrounded by a burst of brilliant happy blue aura radiating outward like ripples, small splashes and water droplets catching golden light, other penguins nearby seeming to celebrate, sparkling water surface reflecting the blue glow, warm and triumphant atmosphere, adorable and heartwarming moment',
        sceneDescription: 'The baby penguin succeeds in swimming',
        layout: 'full-bleed-text-top' as const,
        imageComposition: 'keep main subject in lower two-thirds, simpler background at top for text',
      },
      {
        pageNumber: 12,
        text: `Near the garden fountain, ${childName} spotted a magnificent peacock with its tail feathers fanned wide. Its aura was a dazzling rainbow of pride, each feather eye-spot glowing with a different jewel color — emerald, sapphire, amethyst, and ruby.`,
        imagePrompt: 'A magnificent peacock with its full tail feathers displayed in a grand fan, each eye-spot glowing with different jewel-toned colors of emerald green sapphire blue deep amethyst purple and ruby red, a rainbow aura radiating from the entire display, an ornate stone fountain with flowing water in the background, manicured garden hedges and roses, dazzling light refracting through the aura creating prismatic effects on the ground, regal and stunning atmosphere',
        sceneDescription: `${childName} admires the proud peacock's rainbow aura`,
        layout: 'dramatic-image-only' as const,
        imageComposition: 'full cinematic composition, peacock display as the main subject, no humans',
      },
      {
        pageNumber: 13,
        text: `${childName} hurried back to the lonely elephant. "I know where your family is!" she said. She led her to the hill at the edge of the zoo, where a hidden gate opened to the elephant sanctuary beyond.`,
        imagePrompt: 'A lush green hillside with a large rustic wooden gate partially hidden by flowering vines and purple wisteria, the gate slightly open revealing a vast green sanctuary beyond with rolling hills and a sparkling lake, a path of golden light leading up to the gate, warm afternoon sunlight illuminating the scene, wildflowers in pink and purple blooming along the hillside path, hopeful and adventurous atmosphere, a gentle blue glow visible approaching the gate',
        sceneDescription: `${childName} leads the elephant to the sanctuary gate`,
        layout: 'full-bleed-text-center' as const,
        imageComposition: 'place subjects at edges/sides, keep center softer for text readability',
      },
      {
        pageNumber: 14,
        text: `As the gate swung open, a thunderous trumpeting echoed from the valley below. The lonely elephant raised her trunk and called back! Her blue aura began to shift, swirling with warm golden streaks of hope and happiness.`,
        imagePrompt: 'A wide open sanctuary gate revealing a vast green valley with a herd of five elephants in the distance trumpeting with raised trunks, visible sound waves rippling through the air in golden light, one large elephant in the foreground with its aura transforming from deep blue to swirling blue and gold, dramatic lighting with sun rays breaking through clouds, emotional and triumphant atmosphere, the valley lush and green with a sparkling winding river',
        sceneDescription: 'The elephant hears her family and her aura transforms',
        layout: 'full-bleed-text-bottom' as const,
        imageComposition: 'keep main subject in upper two-thirds, simpler background at bottom for text',
      },
      {
        pageNumber: 15,
        text: `The elephant turned to ${childName} and gently touched her cheek with her trunk. She felt a wave of warmth and gratitude wash over her. Then the elephant walked through the gate toward her family, her aura now a brilliant, joyful gold.`,
        imagePrompt: 'A majestic elephant walking away through an open gate toward a distant herd of elephants on green rolling hills, its aura now a brilliant radiant gold that streams behind it like a cape of light, the other elephants in the distance also glowing gold with welcome, golden particles floating in the air like celebration confetti, beautiful sunset colors in the sky with pink and orange clouds, emotional reunion atmosphere, warm and triumphant',
        sceneDescription: 'The elephant reunites with her herd',
        layout: 'image-right-text-left' as const,
        imageComposition: 'place subject on the RIGHT side, leave left side as soft background',
      },
      {
        pageNumber: 16,
        text: `${childName} walked home from the zoo with a warm glow in her own heart. She had learned that even without words, feelings can shine through. And sometimes, all someone needs is a friend who listens with their heart.`,
        imagePrompt: 'A beautiful zoo exit gate at golden hour with warm sunset light streaming through, the path behind showing the zoo with soft colorful auras still visible from various enclosures in blue turquoise gold silver and rainbow, fireflies beginning to appear in the warm evening air, pink and white flowers lining the cobblestone exit path, a warm golden glow emanating from the center of the scene like a heart shape, peaceful magical ending atmosphere, warm and cozy feeling',
        sceneDescription: `${childName} leaves the zoo with a warm heart and new understanding`,
        layout: 'text-heavy-vignette' as const,
        imageComposition: 'soft vignette edges with warm center glow, text-friendly composition',
      },
    ],
  };
}
