import type { StoryOutputInput } from '@bookmagic/shared';

export function getZooAdventureBoyStory(childName: string, childAge: number, childGender: string): StoryOutputInput {
  return {
    title: `${childName}'s Magical Zoo Adventure!`,
    pages: [
      {
        pageNumber: 1,
        text: `${childName}'s Magical Zoo Adventure!`,
        imagePrompt: 'A decorative storybook title page with ornate golden zoo gates framing the edges, glowing colorful animal auras in soft blue gold and silver drifting through the air, lush tropical plants and flowers bordering the page, a magical shimmering path leading through the gates into a wonderland zoo, warm inviting golden light',
        sceneDescription: 'Title page with magical zoo-themed decorations',
        layout: 'chapter-title' as const,
        imageComposition: 'chapter-title: decorative border with zoo gates and glowing auras',
      },
      {
        pageNumber: 2,
        text: `One bright morning, ${childName} walked through the tall golden gates of the Whispering Zoo. Something felt different today. The air shimmered with tiny flecks of light, and he could feel a warm tingle in his chest.`,
        imagePrompt: 'Tall ornate golden zoo gates opening into a magical pathway lined with lush tropical plants and colorful flowers, tiny golden light particles floating in the air like fireflies in daytime, a cobblestone path winding ahead into a vibrant green landscape, warm morning sunlight streaming through the gates casting long golden rays, shimmering magical atmosphere with soft bokeh light effects',
        sceneDescription: `${childName} enters the magical Whispering Zoo`,
        layout: 'full-bleed-text-bottom' as const,
        imageComposition: 'keep main subject in upper two-thirds, simpler background at bottom for text',
      },
      {
        pageNumber: 3,
        text: `As ${childName} rounded the first corner, he gasped. Every animal in the zoo was surrounded by a softly glowing aura of color! A sign by the path read: "Today, the animals share their feelings through light."`,
        imagePrompt: 'A wide cobblestone zoo pathway with lush green hedges on both sides, multiple animal enclosures visible in the distance each radiating soft colorful glowing auras in blue gold pink and green, an ornate wooden sign with golden lettering beside the path, magical sparkles drifting upward from the enclosures, bright blue sky with fluffy white clouds, vibrant and enchanting atmosphere',
        sceneDescription: `${childName} discovers the animals have glowing auras`,
        layout: 'full-bleed-text-top' as const,
        imageComposition: 'keep main subject in lower two-thirds, simpler background at top for text',
      },
      {
        pageNumber: 4,
        text: `The first enclosure held a magnificent elephant. But unlike the other animals, its aura glowed a deep, lonely blue. The elephant stood apart from the others, its trunk curled sadly. ${childName} felt his heart ache just looking at it.`,
        imagePrompt: 'A large majestic African elephant standing alone in a spacious lush green enclosure, surrounded by a deep melancholy blue glowing aura that pulses gently, the elephant trunk curled downward with sad drooping ears, tall acacia trees in the background, soft blue light casting shadows on the ground, other distant warm glows visible from neighboring enclosures contrasting with the blue sadness, emotional and tender atmosphere',
        sceneDescription: `${childName} meets the lonely elephant with a blue aura`,
        layout: 'image-left-text-right' as const,
        imageComposition: 'place subject on the LEFT side, leave right side as soft background',
      },
      {
        pageNumber: 5,
        text: `"Why are you so sad?" ${childName} whispered. The elephant looked at him with wise, ancient eyes. Somehow, he understood: she had been separated from her herd long ago and missed them terribly.`,
        imagePrompt: 'A close-up view of a large elephant face with wise ancient amber eyes glistening with emotion, a deep blue glowing aura surrounding the elephant like gentle mist, a single tear trailing down the wrinkled grey skin, soft warm background light filtering through acacia tree branches, intimate and emotional atmosphere, beautiful detail on elephant skin texture and long eyelashes',
        sceneDescription: `${childName} senses the elephant's loneliness`,
        layout: 'full-bleed-text-center' as const,
        imageComposition: 'place subjects at edges/sides, keep center softer for text readability',
      },
      {
        pageNumber: 6,
        text: `${childName} promised the elephant he would help. But first, the zoo had more wonders to show him. He followed the sparkly path to a wide open area where a troupe of monkeys swung through the trees, leaving trails of golden sparkles wherever they went!`,
        imagePrompt: 'A lush tropical canopy area with tall trees and thick green vines, five playful monkeys swinging through branches leaving trails of brilliant golden sparkles behind them like comets, golden light particles showering down like glitter, vibrant green leaves and colorful tropical flowers, joyful and energetic atmosphere, warm sunlight filtering through the canopy creating dappled light patterns',
        sceneDescription: `${childName} discovers the playful monkey troupe with golden sparkles`,
        layout: 'full-bleed-text-bottom' as const,
        imageComposition: 'keep main subject in upper two-thirds, simpler background at bottom for text',
      },
      {
        pageNumber: 7,
        text: `The monkeys chattered and giggled, their golden auras bouncing and sparkling with pure joy. One little monkey tossed a sparkly banana-shaped light toward ${childName}, and he caught it! It felt warm and tickly in his hands.`,
        imagePrompt: 'A close view of playful capuchin monkeys on thick tree branches surrounded by brilliant golden sparkling auras, one small monkey reaching out with a glowing golden banana-shaped light in its tiny hand, golden sparkles and light particles floating everywhere like a celebration, lush green tropical leaves framing the scene, warm joyful golden light suffusing the entire atmosphere, magical and playful mood',
        sceneDescription: `A monkey tosses ${childName} a sparkly gift`,
        layout: 'image-right-text-left' as const,
        imageComposition: 'place subject on the RIGHT side, leave left side as soft background',
      },
      {
        pageNumber: 8,
        text: `Next, ${childName} came to a tall ancient tree where three wise owls perched on mossy branches. Their auras shimmered with calm silver light that seemed to whisper secrets of the forest.`,
        imagePrompt: 'A magnificent ancient gnarled tree with thick mossy branches in a quiet corner of the zoo, three wise owls with large luminous eyes perched on different branches, each surrounded by a shimmering silver aura that radiates peaceful wisdom, silver light particles drifting slowly downward like gentle snow, soft purple twilight atmosphere despite being daytime, mystical and serene mood, intricate bark texture with glowing moss',
        sceneDescription: `${childName} meets the wise owls with silver auras`,
        layout: 'dramatic-image-only' as const,
        imageComposition: 'full cinematic composition, owls as the main subjects on the ancient tree, no humans',
      },
      {
        pageNumber: 9,
        text: `The owls blinked slowly at ${childName}. Through their silver glow, he understood their message: "The lonely elephant's herd is in the sanctuary beyond the hill. She needs only to hear their call." ${childName} knew what he had to do.`,
        imagePrompt: 'Three majestic owls with piercing golden eyes on a mossy branch, silver aura intensifying around them as silver light streams outward in gentle waves carrying tiny symbol-like patterns, a faint image of rolling green hills visible in the silver mist behind them, mystical ancient tree bark covered in soft glowing moss, ethereal and wise atmosphere, silver particles forming a path pointing toward distant hills',
        sceneDescription: 'The owls reveal the location of the elephant herd',
        layout: 'full-bleed-text-bottom' as const,
        imageComposition: 'keep main subject in upper two-thirds, simpler background at bottom for text',
      },
      {
        pageNumber: 10,
        text: `On his way back to the elephant, ${childName} passed by the nursery area. There, a baby giraffe was trying to stand on its wobbly, impossibly long legs. It stumbled, got up, stumbled again, and let out a tiny determined huff.`,
        imagePrompt: 'An adorable baby giraffe with large brown eyes and tiny ossicones on a soft grassy nursery area, its long spindly legs splayed awkwardly as it tries to stand, a soft warm orange-pink aura glowing around it showing determination, green grass and white daisies on the ground, a wooden nursery fence in the background, warm afternoon sunlight, endearing and heartwarming atmosphere, the giraffe spots are still fuzzy and light',
        sceneDescription: `${childName} watches a baby giraffe learning to walk`,
        layout: 'image-left-text-right' as const,
        imageComposition: 'place subject on the LEFT side, leave right side as soft background',
      },
      {
        pageNumber: 11,
        text: `${childName} cheered quietly for the little giraffe. "You can do it!" Finally, the baby giraffe stood tall on all four legs, its aura bursting into a proud warm orange glow. He clapped his hands and kept walking with a big smile.`,
        imagePrompt: 'A baby giraffe standing triumphantly on all four legs with its head held high, surrounded by a burst of warm proud orange light radiating outward like a sunrise, small golden sparkles celebrating around it, green meadow with wildflowers, soft warm backlighting creating a heroic silhouette effect, joyful and triumphant atmosphere, the baby giraffe looking proud and happy',
        sceneDescription: 'The baby giraffe succeeds in standing',
        layout: 'full-bleed-text-top' as const,
        imageComposition: 'keep main subject in lower two-thirds, simpler background at top for text',
      },
      {
        pageNumber: 12,
        text: `Near the old baobab tree, a great sleepy lion dozed in a patch of warm sun. Its aura was a soft, peaceful amber that pulsed gently like a slow heartbeat. Even its mighty mane seemed to glow with contentment.`,
        imagePrompt: 'A magnificent male lion with a full golden mane sleeping peacefully under a large baobab tree, surrounded by a soft warm amber aura that pulses gently, dappled sunlight falling on its fur through the baobab leaves, warm savanna grass around it, the aura rising and falling like breathing, peaceful and majestic atmosphere, warm golden tones throughout the scene, butterflies resting on nearby rocks',
        sceneDescription: `${childName} passes the content sleeping lion`,
        layout: 'dramatic-image-only' as const,
        imageComposition: 'full cinematic composition, sleeping lion as the main subject under the tree, no humans',
      },
      {
        pageNumber: 13,
        text: `${childName} hurried back to the lonely elephant. "I know where your family is!" he said. He led her to the hill at the edge of the zoo, where a hidden gate opened to the elephant sanctuary beyond.`,
        imagePrompt: 'A lush green hillside with a large rustic wooden gate partially hidden by flowering vines and ivy, the gate slightly open revealing a vast green sanctuary beyond with rolling hills, a path of golden light leading up to the gate, warm afternoon sunlight illuminating the scene, wildflowers blooming along the hillside path, hopeful and adventurous atmosphere, a gentle blue glow visible approaching the gate from behind',
        sceneDescription: `${childName} leads the elephant to the sanctuary gate`,
        layout: 'full-bleed-text-center' as const,
        imageComposition: 'place subjects at edges/sides, keep center softer for text readability',
      },
      {
        pageNumber: 14,
        text: `As the gate swung open, a thunderous trumpeting echoed from the valley below. The lonely elephant raised her trunk and called back! Her blue aura began to shift, swirling with warm golden streaks of hope and happiness.`,
        imagePrompt: 'A wide open sanctuary gate revealing a vast green valley with a herd of five elephants in the distance trumpeting with raised trunks, visible sound waves rippling through the air in golden light, one large elephant in the foreground with its aura transforming from deep blue to swirling blue and gold, dramatic lighting with sun rays breaking through clouds, emotional and triumphant atmosphere, the valley lush and green with a winding river',
        sceneDescription: 'The elephant hears her family and her aura transforms',
        layout: 'full-bleed-text-bottom' as const,
        imageComposition: 'keep main subject in upper two-thirds, simpler background at bottom for text',
      },
      {
        pageNumber: 15,
        text: `The elephant turned to ${childName} and gently touched his cheek with her trunk. He felt a wave of warmth and gratitude wash over him. Then she walked through the gate toward her family, her aura now a brilliant, joyful gold.`,
        imagePrompt: 'A majestic elephant walking away through an open gate toward a distant herd of elephants on green rolling hills, its aura now a brilliant radiant gold that streams behind it like a cape of light, the other elephants in the distance also glowing gold with welcome, golden particles floating in the air like celebration confetti, beautiful sunset colors in the sky, emotional reunion atmosphere, warm and triumphant',
        sceneDescription: 'The elephant reunites with her herd',
        layout: 'image-right-text-left' as const,
        imageComposition: 'place subject on the RIGHT side, leave left side as soft background',
      },
      {
        pageNumber: 16,
        text: `${childName} walked home from the zoo with a warm glow in his own heart. He had learned that even without words, feelings can shine through. And sometimes, all someone needs is a friend who listens with their heart.`,
        imagePrompt: 'A beautiful zoo exit gate at golden hour with warm sunset light streaming through, the path behind showing the zoo with soft colorful auras still visible from various enclosures in blue gold silver and amber, fireflies beginning to appear in the warm evening air, flowers lining the cobblestone exit path, a warm golden glow emanating from the center of the scene like a heart shape, peaceful magical ending atmosphere, warm and cozy',
        sceneDescription: `${childName} leaves the zoo with a warm heart and new understanding`,
        layout: 'text-heavy-vignette' as const,
        imageComposition: 'soft vignette edges with warm center glow, text-friendly composition',
      },
    ],
  };
}
